require conf/distro/include/tegrademo.inc

INHERIT += "tegra-support-sanity"
ESDK_CLASS_INHERIT_DISABLE:append = " tegra-support-sanity"

BB_SIGNATURE_HANDLER ?= "OEEquivHash"
BB_HASHSERVE ??= "auto"

# Ensure the IMX585 device-tree gets staged on the EFI partition and
# the overlay is packaged with the tegraflash payload for Orin Nano NVMe.
UBOOT_EXTLINUX_FDT:jetson-orin-nano-devkit-nvme = "tegra234-p3768-0000+p3767-0005-oe4t.dtb"
UBOOT_EXTLINUX_FDTOVERLAYS:jetson-orin-nano-devkit-nvme = "imx585-overlay.dtbo"
OVERLAY_DTB_FILE:append:jetson-orin-nano-devkit-nvme = ",imx585-overlay.dtbo"
